
name: 'auto_label_opt_v1'
device: "cuda:0"

l1: 0.01
l2: 1.0 

calib_val_frac: 0.5 

type: post_hoc

#model_conf:   # to be specified

training_conf_g: 
  optimizer: 'sgd'
  learning_rate: 0.07
  batch_size: 64
  max_epochs: 500
  weight_decay: 0.0001
  momentum: 0.9
  use_lr_schedule: True 
  nesterov: False 

training_conf_t: 
  optimizer: 'sgd'
  learning_rate: 0.001
  batch_size: 64
  max_epochs: 200
  weight_decay: 0.0001
  momentum: 0.9
  use_lr_schedule: True 
  nesterov: False 

auto_lbl_conf: 
  auto_label_err_threshold: 0.05
