
name: 'auto_label_opt_v0'

device: "cuda:0"

calib_val_frac: 0.5

type: post_hoc

l1 : 1.0 
l2 : 2.0
l3:  0.0
regularize: False 

class_wise: "independent"

features_key: 'pre_logits'
alpha_1: 0.5

training_conf_g: 
  optimizer: 'sgd'
  learning_rate: 0.07
  batch_size: 64
  max_epochs: 500
  weight_decay: 0.0001
  momentum: 0.9
  use_lr_schedule: True 
  nesterov: False 

training_conf_t: 
  optimizer: 'sgd'
  learning_rate: 0.001
  batch_size: 64
  max_epochs: 200
  weight_decay: 0.0001
  momentum: 0.9
  use_lr_schedule: True 
  nesterov: False 

auto_lbl_conf: 
  auto_label_err_threshold: 0.05
