
name: 'auto_label_opt_v2'
device: "cuda:0"

l1: 1.0
l2: 1.0
l3: 10.0
l4: 1.5 

alpha_1: 1.0

calib_val_frac: 0.6 
regularize: False 
features_key: 'pre_logits'

type: post_hoc

#model_conf:   # to be specified

training_conf_g: 
  optimizer: 'adam'
  learning_rate: 0.0001
  batch_size: 512
  shuffle: True 
  max_epochs: 500
  weight_decay: 0.0001
  momentum: 0.9
  use_lr_schedule: True 
  nesterov: False 

auto_lbl_conf: 
  auto_label_err_threshold: 0.05
  C_1 : 0.25
  
