name: 'dirichlet'
calib_val_frac: 0.6 
type: post_hoc

training_conf: 
  optimizer: 'adam'
  learning_rate: 0.5
  reg: 1e-2
  batch_size: 64
  max_epochs: 50
  shuffle: True 
  log_train_ece: True 
  log_train_ece_freq: 1 
  
