name: 'scaling_binning'
calib_val_frac: 0.6 
type: post_hoc

training_conf: 
  optimizer: 'adam'
  learning_rate: 0.5
  batch_size: 64
  shuffle: True 
  max_epochs: 100
  log_train_ece: True 
  log_train_ece_freq: 1 
  num_bins: 10
