name: "crl"
loss_function: "crl"
rank_target: "softmax" # options : softmax, margin, entropy
rank_weight: 1.0 
optimizer: "sgd"
learning_rate: 0.1
max_epochs: 50
batch_size: 32
weight_decay: 1e-4
momentum: 0.9

